In [17]:
import numpy as np
import pandas as pd

In [18]:
f500 = pd.read_csv('f500.csv',index_col=0)

In [19]:
f500.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
rank                        500 non-null int64
revenues                    500 non-null int64
revenue_change              498 non-null float64
profits                     499 non-null float64
assets                      500 non-null int64
profit_change               436 non-null float64
ceo                         500 non-null object
industry                    500 non-null object
sector                      500 non-null object
previous_rank               500 non-null int64
country                     500 non-null object
hq_location                 500 non-null object
website                     500 non-null object
years_on_global_500_list    500 non-null int64
employees                   500 non-null int64
total_stockholder_equity    500 non-null int64
dtypes: float64(3), int64(7), object(6)
memory usage: 66.4+ KB


In [20]:
f500.describe()

rank       revenues  revenue_change       profits        assets  \
count  500.000000     500.000000      498.000000    499.000000  5.000000e+02   
mean   250.500000   55416.358000        4.538353   3055.203206  2.436323e+05   
std    144.481833   45725.478963       28.549067   5171.981071  4.851937e+05   
min      1.000000   21609.000000      -67.300000 -13038.000000  3.717000e+03   
25%    125.750000   29003.000000       -5.900000    556.950000  3.658850e+04   
50%    250.500000   40236.000000        0.550000   1761.600000  7.326150e+04   
75%    375.250000   63926.750000        6.975000   3954.000000  1.805640e+05   
max    500.000000  485873.000000      442.300000  45687.000000  3.473238e+06   

       profit_change  previous_rank  years_on_global_500_list     employees  \
count     436.000000     500.000000                500.000000  5.000000e+02   
mean       24.152752     222.134000                 15.036000  1.339983e+05   
std       437.509566     146.941961                  7.932752  1.700878e+05   
min      -793.700000       0.000000                  1.000000  3.280000e+02   
25%       -22.775000      92.750000                  7.000000  4.293250e+04   
50%        -0.350000     219.500000                 17.000000  9.291050e+04   
75%        17.700000     347.250000                 23.000000  1.689172e+05   
max      8909.500000     500.000000                 23.000000  2.300000e+06   

       total_stockholder_equity  
count                500.000000  
mean               30628.076000  
std                43642.576833  
min               -59909.000000  
25%                 7553.750000  
50%                15809.500000  
75%                37828.500000  
max               301893.000000

In [26]:
f500.loc[["Anheuser-Busch InBev","Coca-Cola","Heineken Holding"],"rank":"ceo"]

rank  revenues  revenue_change  profits  assets  \
company                                                                 
Anheuser-Busch InBev   206     45905             5.3   1241.0  258381   
Coca-Cola              235     41863            -5.5   6527.0   87270   
Heineken Holding       468     23044            -0.7    861.5   41469   

                      profit_change                        ceo  
company                                                         
Anheuser-Busch InBev          -85.0               Carlos Brito  
Coca-Cola                     -11.2           James B. Quincey  
Heineken Holding              -18.9  Jean-Francois van Boxmeer

In [31]:
toyota = f500.loc["Toyota Motor"]
drink_companies = f500.loc[["Anheuser-Busch InBev","Coca-Cola","Heineken Holding"]]
middle_companies = f500.loc["Tata Motors":"Nationwide","rank":"country"]

In [33]:
sectors = f500["sector"]
sectors.value_counts()

Financials                       118
Energy                            80
Technology                        44
Motor Vehicles & Parts            34
Wholesalers                       28
Health Care                       27
Food & Drug Stores                20
Transportation                    19
Telecommunications                18
Retailing                         17
Materials                         16
Food, Beverages & Tobacco         16
Industrials                       15
Aerospace & Defense               14
Engineering & Construction        13
Chemicals                          7
Hotels, Restaurants & Leisure      3
Business Services                  3
Media                              3
Household Products                 3
Apparel                            2
Name: sector, dtype: int64

In [7]:
taxi = np.genfromtxt('nyc_taxis.csv', delimiter=',', skip_header=True)

In [8]:
zeros = np.zeros([taxi.shape[0], 1])
taxi_modified = np.concatenate([taxi, zeros], axis=1)
print(taxi_modified)
pickup_location_code = taxi_modified[:,5]

[[2.016e+03 1.000e+00 1.000e+00 ... 6.999e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 5.430e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 3.780e+01 2.000e+00 0.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 6.334e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 4.475e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.484e+01 2.000e+00 0.000e+00]]


In [13]:
taxi_modified[pickup_location_code == 2 ,15] = 1
taxi_modified[pickup_location_code == 3 ,15] = 1
taxi_modified[pickup_location_code == 5 ,15] = 1

In [15]:
taxi_modified[20:50,15]

array([0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1.,
       0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0.])

In [16]:
jfk = taxi[taxi[:,6] == 2]
jfk

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 5.280e+01, 1.056e+02,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.730e+01,
        2.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 5.834e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 3.800e+00,
        2.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.834e+01,
        2.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.660e+00, 6.400e+01,
        1.000e+00]])